name: Rust

on:
  push:
    branches: [main, 0.*.x, 1.*.x, 2.*.x]
  pull_request:
    branches: [main, 0.*.x, 1.*.x, 2.*.x]

env:
  CARGO_TERM_COLOR: always
  REDISRS_REDIS_JSON_PATH: "/tmp/librejson.so"
  REDISRS_REDIS_BLOOM_PATH: "/tmp/redisbloom.so"
  REDISRS_TLS_KEY_CA: "/tmp/tls-ca.key"
  REDISRS_TLS_KEY_SERVER: "/tmp/tls-server.key"
  REDISRS_TLS_KEY_CLIENT: "/tmp/tls-client.key"

concurrency:
  group: "${{ github.workflow }}-${{ github.head_ref || github.run_id || github.ref }}"
  cancel-in-progress: true

jobs:
  benchmark:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    env:
      rust_ver: stable
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install DB
        uses: ./.github/actions/install-db
        with:
          db-org: "redis"
          db-name: "redis"
          db-version: 8.0.2

      - name: Install Rust
        uses: dtolnay/rust-toolchain@6c977a6ca4077a0ceb28ffbe03f59d46e9ac8772 # master
        with:
          toolchain: ${{ env.rust_ver }}

      - uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2.9.2

      - name: Benchmark
        run: |
          cargo install critcmp
          cargo bench -p redis --all-features -- --measurement-time 15 --save-baseline changes
          git fetch
          git checkout ${{ github.base_ref }}
          cargo bench -p redis --all-features -- --measurement-time 15 --save-baseline base
          critcmp base changes

      # We check out again, because we switched branches in the last step.
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
