name: Rust

on:
  push:
    branches: [main, 0.*.x, 1.*.x]
  pull_request:
    branches: [main, 0.*.x, 1.*.x]

env:
  CARGO_TERM_COLOR: always
  REDISRS_REDIS_JSON_PATH: "/tmp/librejson.so"

concurrency:
  group: "${{ github.workflow }}-${{ github.head_ref || github.run_id || github.ref }}"
  cancel-in-progress: true

jobs:
  build-and-test:
    needs: []
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      matrix: &db-matrix
        config: [
            # The databases to test with
            #
            # People typically test using recent versions locally. So, to be mindful of resources,
            # CI only tests against the _earliest_ minor for each major version, with latest patch.
            #
            # If minor versions are sufficiently different, CI also tests against the latest minor.
            #
            # When making changes here, also update `README.md` accordingly (grep for `CI runs against`).
            {  db-org: redis, db-name: redis, db-version: 8.8.0, json-module-version: bundled },
          ]

    steps:
      - uses: actions/checkout@v6

      - name: Cache RedisJSON
        if: matrix.config.json-module-version != '' && matrix.config.json-module-version != 'bundled'
        id: cache-redisjson
        uses: actions/cache/restore@v5
        with:
          path: |
            /tmp/librejson.so
          key: ${{ runner.os }}-redisjson-${{ matrix.config.json-module-version }}

      - name: Install DB
        uses: ./.github/actions/install-db
        with:
          db-org: ${{ matrix.config.db-org }}
          db-name: ${{ matrix.config.db-name }}
          db-version: ${{ matrix.config.db-version }}

      - name: Copy bundled RedisJSON into place
        if: matrix.config.json-module-version == 'bundled'
        run: |
          cp "$HOME/db/rejson.so" "$REDISRS_REDIS_JSON_PATH"

      - name: Install Rust
        uses: dtolnay/rust-toolchain/@master
        with:
          toolchain: stable
          components: rustfmt

      - uses: Swatinem/rust-cache@v2

      - name: Install cargo-nextest
        uses: taiki-e/install-action@v2
        with:
          tool: nextest

      - name: Run tests
        run: make hammer
